### ISSUE TITLE
qq does not save settings properly when true blind.

### ISSUE THREAD

**Issue by wurpwurp** [tynil/WunderSys#20]
In wsys.startedqq, it tries to reference gmcp.Room, which is not present if you're true blind (blind with no mindseye). This causes an error (index nil on Info), and your settings will not save.

function wsys.startedqq()
  local roomnum = gmcp.Room.Info.num  --problem line
<<<
 local roomnum = (gmcp.Room and gmcp.Room.Info.num) or 5 --pick a magic number

**Comment by tynil** [comment]
roomnum in that function isn't even used. I'll just remove the line altogether.
